/* eslint-disable */
/*
 * Request to Pay → "LOOP Prompt" docs content (API name: "LOOP Prompt").
 *
 * Same layout/styles as M-PESA STK Push (shared RequestToPayKit). Only the
 * content differs. Every value is taken verbatim from the Figma node
 * (Developer Portal — "Request to Pay_LOOP Prompt" 5307-13367).
 */
import { buildDoc } from './RequestToPayKit';

export const LOOP_PROMPT_DATA = {
    marker: '// REQUEST TO PAY',
    title: 'LOOP Prompt',
    subtitle: "LOOP's native payment initiation method. Sends a payment request notification to the customer's LOOP-registered mobile number. The customer confirms payment within the LOOP application.",
    description: "This endpoint integrates with the M-Pesa payment gateway to initiate an STK Push to the customer's registered mobile number. The transaction is asynchronous — your callBackUrl receives the payment notification on completion.",
    keyCharacteristics: [
        'Customer authorises payment using their M-Pesa PIN on the STK prompt',
        '`payMblNo` must be in international format — e.g. `254XXXXXXXXX`',
        '`refNo` must be unique per request — reusing a reference returns a duplicate error',
        '`callBackUrl` receives the asynchronous payment notification from M-Pesa',
        'Implement exponential backoff and retry with the same refNo on gateway failures — do not generate a new reference if the original transaction may have been partially processed',
    ],
    params: [
        { name: 'refNo', type: 'String', req: 'Yes', desc: 'Unique reference number for the transaction. Generated by the merchant.' },
        { name: 'payMblNo', type: 'String', req: 'Yes', desc: 'Mobile number of the payer in international format (e.g. `254XXXXXXXXX`).' },
        { name: 'merchantId', type: 'String', req: 'Yes', desc: 'Unique identifier for the merchant on the LOOP platform.' },
        { name: 'appId', type: 'String', req: 'Yes', desc: "Application ID associated with the merchant's integration." },
        { name: 'currency', type: 'String', req: 'Yes', desc: 'Currency code for the transaction (e.g. `KES`).' },
        { name: 'tillNo', type: 'String', req: 'Yes', desc: "The merchant's till number to which the payment is directed." },
        { name: 'payAmt', type: 'String', req: 'Yes', desc: 'Amount to be charged to the customer in the specified currency.' },
        { name: 'callBackUrl', type: 'String', req: 'Yes', desc: 'Endpoint URL where the payment notification will be delivered on completion.' },
        { name: 'pmtCnl', type: 'String', req: 'Yes', desc: 'Channel of payment.' },
    ],
    reqTabs: {
        cURL: [
            "curl -X POST 'https://sandbox.loop.co.ke/gateway/pay/v1/loop/prompt' \\",
            "  -H 'Authorization: Bearer YOUR_JWT_TOKEN' \\",
            "  -H 'Content-Type: application/json' \\",
            "  -d '{",
            '    "mobileNo": "254712345678",',
            '    "amount": "100",',
            '    "tillNo": "123456",',
            '    "merchantId": "MERCHANT_001",',
            '    "securityCredential": "Base64EncodedCredential...",',
            '    "callBackUrl": "https://yourdomain.com/callback"',
            "  }'",
        ],
        'Node.js': [
            "const res = await fetch('https://sandbox.loop.co.ke/gateway/pay/v1/loop/prompt', {",
            "  method: 'POST',",
            '  headers: {',
            "    Authorization: 'Bearer YOUR_JWT_TOKEN',",
            "    'Content-Type': 'application/json',",
            '  },',
            '  body: JSON.stringify({',
            "    mobileNo: '254712345678',",
            "    amount: '100',",
            "    tillNo: '123456',",
            "    merchantId: 'MERCHANT_001',",
            "    securityCredential: 'Base64EncodedCredential...',",
            "    callBackUrl: 'https://yourdomain.com/callback',",
            '  }),',
            '});',
            'const data = await res.json();',
        ],
        Python: [
            'import requests',
            'res = requests.post(',
            "    'https://sandbox.loop.co.ke/gateway/pay/v1/loop/prompt',",
            "    headers={'Authorization': 'Bearer YOUR_JWT_TOKEN',",
            "             'Content-Type': 'application/json'},",
            '    json={',
            "        'mobileNo': '254712345678',",
            "        'amount': '100',",
            "        'tillNo': '123456',",
            "        'merchantId': 'MERCHANT_001',",
            "        'securityCredential': 'Base64EncodedCredential...',",
            "        'callBackUrl': 'https://yourdomain.com/callback',",
            '    })',
            'print(res.json())',
        ],
    },
    responseFields: [
        { name: 'orderNo', type: 'String', desc: 'Unique reference number for the transaction order.' },
        { name: 'rspMessage', type: 'String', desc: 'Human-readable response status message (e.g. SUCCESS).' },
        { name: 'orderDate', type: 'String', desc: 'Date the order was placed. Format: YYYYMMDD.' },
        { name: 'orderToken', type: 'String', desc: 'Unique token combining order date and order number for verification.' },
        { name: 'rspCode', type: 'String', desc: 'Response code indicating the result (e.g. `00000000` for success).' },
        { name: 'totalAmount', type: 'String', desc: 'Total transaction amount in the smallest currency unit.' },
        { name: 'signature', type: 'String', desc: 'Base64-encoded HMAC signature for payload integrity verification.' },
        { name: 'loopRefNo', type: 'String', desc: "LOOP's internal unique reference number for the transaction." },
        { name: 'appId', type: 'String', desc: 'Application identifier of the merchant that initiated the request.' },
        { name: 'serverTime', type: 'String', desc: 'Server timestamp at time of response. Format: YYYYMMDDHHmmss.' },
        { name: 'responseId', type: 'String', desc: 'Unique UUID identifying this specific response instance.' },
    ],
    responseJson: [
        '{',
        '  "orderNo": "ORD20260601001",',
        '  "rspMessage": "SUCCESS",',
        '  "orderDate": "20260601",',
        '  "orderToken": "20260601ORD20260601001",',
        '  "rspCode": "00000000",',
        '  "totalAmount": "10000",',
        '  "signature": "Base64EncodedHMACSignatureHere==",',
        '  "loopRefNo": "LOOP-2026060100001",',
        '  "appId": "APP_001",',
        '  "serverTime": "20260601120000",',
        '  "responseId": "550e8400-e29b-41d4-a716-446655440000"',
        '}',
    ],
    errors: [
        { code: '400', desc: 'Missing or invalid request parameters.' },
        { code: '401', desc: 'Invalid or expired Bearer Token. Re-authenticate via the Authorization API.' },
        { code: '404', desc: 'Duplicate transaction reference — `refNo` already exists. Generate a new unique reference.' },
        { code: '503', desc: 'External service failure (e.g. M-Pesa gateway unreachable). Merchant validation failed. Retry with exponential backoff using the same `refNo`.' },
    ],
    note503: 'For 503 errors, implement exponential backoff and retry with the same refNo. Do not generate a new reference on a gateway failure — the original transaction may have been partially processed.',
    faqs: [
        {
            q: "The customer didn't receive the LOOP prompt.",
            a: 'Confirm the customer is registered on the LOOP app and that payMblNo is in international format (254XXXXXXXXX). The prompt appears in the LOOP application — ensure the device has connectivity, then retry with the same refNo.',
        },
        {
            q: 'What is the difference between M-Pesa STK Push and LOOP Prompt?',
            a: 'STK Push delivers the prompt via the Safaricom SIM Toolkit and is authorised with the M-Pesa PIN on the handset. LOOP Prompt is LOOP\'s native flow — the request appears inside the LOOP application, where the customer confirms the payment.',
        },
        {
            q: 'What scene values are supported?',
            a: 'Use the payment-channel value (pmtCnl) appropriate to your integration. Refer to the channel reference in the integration guide for the list of supported values.',
        },
        {
            q: 'How do I get notified when the payment completes?',
            a: 'The transaction is asynchronous. Once the customer confirms (or declines) in the LOOP app, the final notification is posted to your callBackUrl, which must be publicly reachable.',
        },
    ],
};

const doc = buildDoc(LOOP_PROMPT_DATA);

export const LOOP_PROMPT_TOC = doc.toc;
export const LoopPromptIntro = doc.intro;
export const LoopPromptMiddle = doc.middle;
export const LoopPromptEnd = doc.end;

export default LoopPromptMiddle;
